=== Alvar0dev/Lenguaje-de-Marcas/Hola_xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="alumnos"> <!--Elemento
        raiz va aqui-->
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded"> <!-- maxOccurs="unbounded (aparecera
                    una o mas veces)"-->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellidos" type="xs:string" />
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer"> <!-- Si esta declarado dentro
                                        de la restricion no hace falta ponerlo en el elemento-->
                                        <xs:minInclusive value="18" />
                                        <xs:maxInclusive value="100" /> <!-- Rango de intevalo
                                        permitido-->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ciclo" type="xs:string" />
                            <xs:element name="nota_media" type="xs:integer" />
                        </xs:sequence>
                        <xs:attribute name="expediente">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0" />
                                    <xs:maxInclusive value="9999" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <!--Los
                        atributos una etiqueta compleja con mas elementos dentro se pone fuera de la
                        secuencia de elementos que contiene-->
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Alvar0dev/Lenguaje-de-Marcas/Hola_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Declaracion con version y encoding-->

<?xml-model href="hola_xml.xsd" type="application/xml" schemaLocation="hola_xml.xsd"?>

<!-- DTD - Aqui se coloca el DTD y establece los elementos y que atributos pueden tener -->
<!DOCTYPE alumnos [
    <!ELEMENT alumnos (alumno+)> <!-- + (una o mas veces) * (cero o mas veces) ?(puede o no
    aparecer)-->
    <!ATTLIST alumnos> <!-- CDATA (Caracteres de datos)-->
    <!-- #REQUIRED (Requerido) #IMPLIED (Opcional)-->
    <!ELEMENT alumno (nombre, apellidos, edad, ciclo,nota_media)>
    <!ATTLIST alumno expediente CDATA #REQUIRED>
    <!-- Aqui se colocan los elementos  que estaran dentro de alumno -->

    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT ciclo (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>
    <!ELEMENT nota_media (#PCDATA)>
]>
<alumnos>
    <alumno expediente="1000">
        <nombre>Alvaro</nombre>
        <apellidos>Perez</apellidos>
        <edad>22</edad>
        <ciclo>DAW</ciclo>
        <nota_media>8</nota_media>
    </alumno>

    <alumno expediente="1001">
        <nombre>Carlos</nombre>
        <apellidos>Jimenez</apellidos>
        <edad>21</edad>
        <ciclo>DAM</ciclo>
        <nota_media>9</nota_media>
    </alumno>

    <alumno expediente="1002">
        <nombre>Antonio</nombre>
        <apellidos>Santos</apellidos>
        <edad>26</edad>
        <ciclo>ASIR</ciclo>
        <nota_media>7</nota_media>
    </alumno>
</alumnos>
